name: blue-triangle-marker
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          curl --request POST \
           --url https://api.bluetriangle.com/event-markers \
           --header 'Content-Type: application/json' \
           --header 'X-API-Email: ${{ secrets.BLUE_TRIANGLE_EMAIL }}' \
           --header 'X-API-Key: ${{ secrets.BLUE_TRIANGLE_API_KEY }}' \
           --data '{"prefix": "dsg2",
          "eventStart": "1536552000",
          "eventType": "site",
          "eventName": "Testing Actions",
          "annotation": "API Actions Test",
          "lineColor": "yellow",
          "lineThickness": "normal",
          "lineStyle": "dotted",
          "timezone": "America/New_York",
          "description": "This is a github test"}'
