on: [push]
name: build
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get epoch date
        id: date
        run: echo "::set-output name=EPOCH_DATE::$(date +'%s')"
      - name: Test with environment variables
        run: echo $BT_EVENT_MARKER
        env:
          BT_EVENT_MARKER: release-${{ steps.date.outputs.date }}
      - name: Create BT Event Marker
        run: |
          curl --request POST \
            --url https://api.bluetriangletech.com/event-markers \
            --header 'Content-Type: application/json' \
            --header 'X-API-Email: ${{ secrets.BLUE_TRIANGLE_EMAIL }}' \
            --header 'X-API-Key: ${{ secrets.BLUE_TRIANGLE_API_KEY }}' \
            --data '{"prefix": "dsg2",
          "eventStart": "${{ steps.date.outputs.date }}",
          "eventType": "site",
          "eventName": "Actions Test 8",
          "annotation": "Secrets Testing",
          "lineColor": "yellow",
          "lineThickness": "normal",
          "lineStyle": "solid",
          "timezone": "America/New_York",
          "description": "this was a test"}'
