name: blue-triangle-marker
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          curl --request POST \
            --url https://api.bluetriangletech.com/event-markers \
            --header 'Content-Type: application/json' \
            --header 'X-API-Email: Stephanie.Symosko@dcsg.com' \
            --header 'X-API-Key: ab243bfe4012b551a607b741e23b4850' \
            --data '{"prefix": "dsg2",
          "eventStart": "1536552000",
          "eventType": "site",
          "eventName": "Actions Test 1",
          "annotation": "API Testing",
          "lineColor": "yellow",
          "lineThickness": "normal",
          "lineStyle": "solid",
          "timezone": "America/New_York",
          "description": "this was a test"}'
