# This is a manually triggered workflow that takes an input

name: manual-input-workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Event Marker name'
        default: 'Manual Test'
        required: true
      annotation:
        description: 'Event annotation'
        default: 'What is the update?'
        required: true
      eventDate:
        description: 'Start date for event'
        default: 'Format like YearMonthDayHourMinSec'
        required: true
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Get today's date
      id: todaysdate
      run: echo "::set-ouput name=date::$v(date +'%Y.%m.%d-%H%M%S')"
    - name: Print today's date
      run: echo "This is today's date :" ${{ steps.todaysdate.outputs.todaysdate }}
    - name: Set epoch date
      id: epochdate
      run: echo "::set-output name=epochdate::$(date +'%s')"
    - name: Print Epoch Date
      run: echo "This is the epoch date :" ${{ steps.epochdate.outputs.epochdate }}
    - name: Send Event Marker
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Show annotation message
      run: echo "This is what the annotation will say ${{ github.event.inputs.annotation }}"
